### ISSUE TITLE
x11vnc (exit status 1; not expected)

### ISSUE THREAD

**Issue by bluefchen** [furacas/wine-vnc-box#2]
https://github.com/bluefchen/wxhelper-docker/actions/runs/5804616406/job/15734445993#step:7:1347

#14 431.4 2023-08-09 11:49:03,341 INFO spawned: 'x11vnc' with pid 497
#14 432.4 2023-08-09 11:49:04,355 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
#14 432.4 2023-08-09 11:49:04,359 INFO exited: x11vnc (exit status 1; not expected)
#14 433.4 2023-08-09 11:49:05,362 INFO spawned: 'x11vnc' with pid 498
#14 434.4 2023-08-09 11:49:06,375 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
#14 434.4 2023-08-09 11:49:06,378 INFO exited: x11vnc (exit status 1; not expected)
#14 435.4 2023-08-09 11:49:07,382 INFO spawned: 'x11vnc' with pid 499
#14 436.3 Error: Can't open display: (null)
#14 436.3 Failed creating new xdo instance
#14 436.3 1

vnc 会偶现退出并无法启动的情况。 本地能稳定复现，  git ci 中会偶现

**Comment by furacas** [comment]
最新版已经修复了该问题。可以拉一下最新的镜像试试。

**Comment by furacas** [comment]
fixed https://github.com/furacas/wine-vnc-box/releases/tag/v1.3.2
